name: Build gh-pages

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and publish to gh-pages
      run: |
        npm install
        npm run build --if-present
        npm publish dist
      shell: bash
      if: github.event == 'push'
      env:
        CI: true
